### ISSUE TITLE
Exception when indexing product with ES

### ISSUE THREAD

**Issue by jvelo** [mayocat/mayocat-shop#236]
```
ERROR [2015-02-27 20:30:02,009] org.mayocat.search.elasticsearch.ElasticSearchSearchEngine: Failed to index entity upon update
! java.lang.ClassCastException: java.util.Locale cannot be cast to java.lang.String
! at org.elasticsearch.common.xcontent.support.XContentMapConverter.writeMap(XContentMapConverter.java:123) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.common.xcontent.support.XContentMapConverter.writeValue(XContentMapConverter.java:172) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.common.xcontent.support.XContentMapConverter.writeMap(XContentMapConverter.java:128) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.common.xcontent.support.XContentMapConverter.writeValue(XContentMapConverter.java:172) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.common.xcontent.support.XContentMapConverter.writeMap(XContentMapConverter.java:128) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:1113) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:339) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:327) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.elasticsearch.action.index.IndexRequestBuilder.setSource(IndexRequestBuilder.java:106) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.mayocat.search.elasticsearch.ElasticSearchSearchEngine.index(ElasticSearchSearchEngine.java:136) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! ... 66 common frames omitted
! Causing: org.mayocat.search.SearchEngineException: Failed to index entity
! at org.mayocat.search.elasticsearch.ElasticSearchSearchEngine.index(ElasticSearchSearchEngine.java:147) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.mayocat.search.elasticsearch.ElasticSearchSearchEngine.index(ElasticSearchSearchEngine.java:123) ~[mayocat-shop-application-0.40-SNAPSHOT.jar:na]
! at org.mayocat.search.elasticsearch.ElasticSearchSearchEngine$SearchEngineEventListener.onEvent(ElasticSearchSearchEngine.java:95) ~[mayocat-shop-application-0.40-SNAPSHOT.ja
r:na]
```

**Comment by jvelo** [comment]
Duplicate of #117
